// Author: Ryan Alderton
// SID: 1609275
using System;
using System.Data;
using System.Data.SqlClient;

namespace BasicGP
{
    class DBAccess
    {
        private static string conStr = Properties.Settings.Default.OverGPDBConnectionString;
        private static SqlConnection DBConnection;
        private static SqlDataAdapter loginDataAdapter;
        private static SqlDataAdapter dataAdapter;


        /// <summary>
        /// Opens the connection based on the string passed in DatabaseConnection
        /// </summary>
        public static void OpenConnection()
        {
            DBConnection = new SqlConnection(conStr);
            DBConnection.Open();
        }

        /// <summary>
        /// Closes the DB Connection
        /// </summary>
        public static void CloseConnection()
        {
            DBConnection.Close();
        }
        
        /// <summary>
        /// Get the data generated by the SQL Statment
        /// </summary>
        /// <param name="sqlQuery">The SQL query to passed in</param>
        /// <returns></returns>
        public static DataSet CheckLogin(string username, string password)
        {
            DataSet loginDataSet;
            //Open a connection to the database inside DBAccess
            OpenConnection();
            //create the object dataAdapter to manipulate a table from the database specified by DBConnection
            loginDataAdapter = new SqlDataAdapter($"SELECT * FROM users WHERE userName = '{username}' AND password = '{password}'", DBConnection);
            //Creat the dataSet
            loginDataSet = new DataSet();
            loginDataAdapter.Fill(loginDataSet);
            //close the DB Connections
            CloseConnection();

            return loginDataSet;
        }

        /// <summary>
        /// Gets data from DB
        /// </summary>
        /// <param name="data"></param>
        /// <returns></returns>
        public static DataSet getData(params string[] data)
        {
            DataSet dataSet;

            dataSet = null;
            dataAdapter = null;

            OpenConnection();
            
            switch(data[0])
            {
                case "findPatient":
                    int pID = Int32.Parse(data[1]);
                    dataAdapter = new SqlDataAdapter($"SELECT * FROM patient WHERE Id = '{pID}'", DBConnection);
                    break;
                case "patientAppointments":
                    break;
                case "testResults":
                    break;
                case "patientPresciptions":
                    break;
                case "availability":
                    break;
                case "duty":
                    break;
                default:
                    dataSet = null;
                    Console.WriteLine("default");
                    break;
            }

            dataSet = new DataSet();
            dataAdapter.Fill(dataSet);
            CloseConnection();
            return dataSet;
        }

    }
}
